version: '3'
services:
  my-portfolio:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local  # Ensure your .env.local file is included
